export const dishes = [
  {
    name: 'Pizza Margherita',
    price: 9.5,
    description: 'Mozzarella cheese, tomato sauce ',
    image: '../assets/images/pizza-margherita.jpg',
    availability: true,
    allergenes: 'A, C, G',
    story: `Pizza Margherita is a classic and timeless Italian pizza known for its
            simplicity and delicious combination of flavors. This pizza is a true
            representation of the Italian flag with its red tomatoes, white
            mozzarella cheese, and green basil leaves.`,
  },
  {
    name: 'Pizza Cardinale',
    price: 11,
    description: 'ham, cheese, tomato sauce',
    image: '../assets/images/pizza-prosciutto.jpg',
    availability: true,
    allergenes: 'A, C, G',
    story: `Pizza Cardinale is an Italian pizza that exudes a sense of regal indulgence. This majestic pie begins with a meticulously baked crust, offering the perfect base for a luscious tomato sauce. But what makes Pizza Cardinale truly special is its crowning glory a regal duo of artichoke hearts and flavorful ham. These ingredients, chosen with the utmost care, create a harmonious blend of textures and tastes that is nothing short of a royal feast. The artichoke hearts add a touch of elegance with their delicate, slightly nutty flavor, while the ham brings a savory, smoky richness to every bite. Topped off with creamy mozzarella cheese, Pizza Cardinale is a slice of Italian royalty that promises a palate-pleasing experience fit for a king or queen.`,
  },
  {
    name: 'Pizza Salami',
    price: 12,
    description: 'salami, cheese, tomato sauce',
    image: '../assets/images/pizza-salami.jpg',
    availability: true,
    allergenes: 'A, C, G',
    story: `Pizza Salami is an Italian classic that tantalizes the taste buds with its bold and zesty flavors. It begins with a thin, crisp crust, slathered in a tangy tomato sauce that provides the perfect canvas for the star ingredient: slices of savory, spicy salami. The salami's robust flavor, combined with the creamy, golden mozzarella cheese, creates a delicious contrast that's both smoky and slightly fiery. Each bite is a journey into the heart of Italy, delivering a mouthwatering fusion of textures and tastes, and a perfect balance between spice and cheese. It's the pizza for those who crave a little extra kick in their slice.`,
  },
  {
    name: 'Pizza Funghi',
    price: 10,
    description: 'mushrooms, cheese, tomato sauce',
    image: '../assets/images/pizza-funghi.jpg',
    availability: false,
    allergenes: 'A, C, G',
    story: `Pizza Funghi is a savory delight that celebrates the earthy richness of mushrooms. This Italian classic features a perfectly baked crust, smothered with a velvety    tomato sauce. On top of this canvas, a generous helping of sliced mushrooms, often sautéed for an intensified flavor, creates a delightful harmony with the creamy mozzarella cheese. It's a pizza that offers a symphony of flavors, combining the umami goodness of mushrooms with the comfort of melted cheese, resulting in a delightful slice that's both hearty and satisfying.`,
  },
  {
    name: 'Pizza Rucola',
    price: 13,
    description: 'prosciutto ,rocket, parmesan cheese, tomato sauce',
    image: '../assets/images/pizza-rucola.jpg',
    availability: true,
    allergenes: 'A, C, G',
    story: `Pizza Prosciutto and Rocket is a delightful Italian creation that combines the savory charm of prosciutto with the crisp, peppery freshness of rocket (arugula). This pizza starts with a thin, perfectly baked crust as the canvas, adorned with a thin layer of tomato sauce for a touch of zest. But the real magic happens when tender slices of prosciutto are artfully draped across the pizza, offering a luxurious and slightly salty flavor that harmonizes beautifully with the earthy arugula. The rocket, with its peppery bite, adds a refreshing contrast and a burst of green vibrancy. Together with mozzarella cheese, this pizza is a masterpiece of balance, offering a delightful mix of flavors and textures, making each bite a refreshing and savory experience. It's a true Italian delicacy for those who appreciate the interplay of bold and fresh flavors.`,
  },
  {
    name: 'Pizza Disgrace',
    price: 15,
    description: 'ham, pineapple cheese, tomato sauce',
    image: '../assets/images/pizza-hawai.png',
    availability: true,
    allergenes: 'A, C, G',
    story: `Ah, the infamous Pizza Hawaii the 'pineapple on pizza' crime scene. Some say it's the lovechild of a pizza and a tropical vacation gone horribly wrong. If you're brave enough to order this culinary oddity, prepare for the sweet and salty showdown that leaves your taste buds wondering, 'Who invited the pineapple to this pizza party?' But hey, to each their own, right? Just remember, while you enjoy your 'exotic' slice, the rest of us will be happily munching on traditional pies that don't require a passport to enjoy!`,
  },
  {
    name: 'Spaghetti Carbonara',
    price: 12,
    description: 'bacon, parmesan cheese, egg yolk',
    image: '../assets/images/carbonara.jpg',
    availability: true,
    allergenes: 'A, C, G',
    story: `Spaghetti Carbonara is a beloved Roman pasta dish that embodies simple elegance. It begins with perfectly al dente spaghetti, cooked to a precise point of tenderness. What truly sets it apart is the luscious sauce, made from eggs, Pecorino Romano cheese, and crispy pancetta. This combination creates a creamy, flavorful coating that clings to the strands of spaghetti, resulting in a sumptuous and savory symphony of flavors. With a sprinkle of freshly cracked black pepper and a dusting of extra cheese, Spaghetti Carbonara is a timeless classic, celebrated for its uncomplicated perfection and the rich history it brings to your plate.`,
  },
  {
    name: 'Spaghetti Bolognese',
    price: 11,
    description: 'minced meat, carrots, celery, parmesan cheese, tomato sauce',
    image: '../assets/images/bolognese.jpg',
    availability: true,
    allergenes: 'A, C, G,',
    story: `Spaghetti Bolognese is a comforting Italian classic that fills both your heart and your plate. It begins with perfectly cooked al dente spaghetti, the ideal partner for the hearty Bolognese sauce. This sauce is a flavorful medley of ground meat, often a mix of beef and pork, sautéed with onions, garlic, and tomatoes. Slowly simmered to perfection, it becomes a rich, meaty masterpiece. As the spaghetti becomes entwined with the sauce, each bite delivers a satisfying blend of meatiness, tomato tang, and the subtle undertones of aromatic herbs. Topped with a generous sprinkle of Parmesan or Pecorino cheese, Spaghetti Bolognese is the ultimate Italian comfort food, promising warmth and contentment in every forkful.`,
  },
  {
    name: 'Spaghetti alla Genovese',
    price: 9,
    description: 'garlic, parmesan cheese, basil pesto',
    image: '../assets/images/genovese.jpg',
    availability: true,
    allergenes: 'A, C, G',
    story: `Spaghetti alla Genovese is a delightful Italian dish that hails from the vibrant region of Genoa. It features tender, perfectly cooked spaghetti as its base, creating a harmonious relationship with a fragrant, basil-infused sauce. What truly distinguishes this dish is the slow-cooked onion sauce that envelops the pasta. These onions are sautéed until they become meltingly soft and sweet, offering a unique and delicate flavor. Complemented by fresh basil, the sauce becomes a symphony of savory and herbaceous notes that meld with the spaghetti, providing a mouthwatering experience of simplicity and sophistication. With a final flourish of grated Parmesan cheese, Spaghetti alla Genovese is a culinary ode to the flavors of Italy's Genoa, where every bite feels like a serene stroll through a Mediterranean garden.`,
  },
  {
    name: 'Tiramisu',
    price: 5.5,
    description: 'ladyfingers cookies, mascarpone, coffee, eggs',
    image: '../assets/images/tiramisu.jpg',
    availability: false,
    allergenes: 'A, C, G',
    story: `Tiramisu, often referred to as "pick-me-up" in Italian, is a luscious dessert that's nothing short of a culinary masterpiece. This classic Italian sweet treat is built in layers, with each component contributing to its seductive charm. The foundation is a delicate assembly of coffee-soaked ladyfingers, each soaked in a rich espresso that imparts a gentle coffee kick. They are layered with a velvety mixture of mascarpone cheese, sugar, and egg yolks, creating a creamy, sweet embrace for the soaked ladyfingers. The entire creation is crowned with a dusting of cocoa powder or dark chocolate shavings, adding a touch of elegance and the perfect balance to the sweetness. Tiramisu is an indulgence that engages all the senses, offering a symphony of textures and flavors that is both heavenly and impossible to resist. It's a dessert that invites you to savor the artistry of Italian cuisine with every delectable bite.`,
  },
];
