export const dishes = [
  {
    name: 'Pizza Margherita',
    price: 10,
    description: 'Mozzarella cheese, tomato sauce ',
    image: '../assets/images/pizza-margherita.jpg',
    availability: true,
  },
  {
    name: 'Pizza Prosciutto',
    price: 13,
    description: 'ham, cheese, tomato sauce',
    image: '../assets/images/pizza-prosciutto.jpg',
    availability: true,
  },
  {
    name: 'Pizza Salami',
    price: 12,
    description: 'salami, cheese, tomato sauce',
    image: '../assets/images/pizza-salami.jpg',
    availability: true,
  },
  {
    name: 'Pizza Funghi',
    price: 12,
    description: 'mushrooms, cheese, tomato sauce',
    image: '../assets/images/pizza-funghi.jpg',
    availability: false,
  },
  {
    name: 'Pizza Rucola',
    price: 12,
    description: 'prosciutto ,rocket, parmesan cheese, tomato sauce',
    image: '../assets/images/pizza-rucola.jpg',
    availability: true,
  },
  {
    name: 'Pizza Disgrace',
    price: 12,
    description: 'ham, pineapple cheese, tomato sauce',
    image: '../assets/images/pizza-hawai.png',
    availability: false,
  },
  {
    name: 'Spaghetti Carbonara',
    price: 12,
    description: 'bacon, parmesan cheese, egg yolk',
    image: '../assets/images/carbonara.jpg',
    availability: true,
  },
  {
    name: 'Spaghetti Bolognese',
    price: 12,
    description: 'minced meat, carrots, celery, parmesan cheese, tomato sauce',
    image: '../assets/images/bolognese.jpg',
    availability: true,
  },
  {
    name: 'Tiramisu',
    price: 12,
    description: 'ladyfingers cookies, mascarpone, coffee, eggs',
    image: '../assets/images/tiramisu.jpg',
    availability: false,
  },
];
